// ═══════════════════════════════════════════════════════════════════════════
// BENNY'S COFFEE - Data Constants
// All static data for the website
// ═══════════════════════════════════════════════════════════════════════════

export const menuData = {
  breakfast: [
    {
      id: 101,
      name: 'French Toast',
      description: 'Soft sweet French toast served Benny’s style',
      price: '50',
      tag: 'Sweet',
    },
    {
      id: 102,
      name: 'French Toast Nutella',
      description: 'French toast served with Nutella',
      price: '55',
      tag: 'Sweet',
    },
    {
      id: 103,
      name: 'Tuna Melt',
      description: 'Warm toast with tuna and melted cheese',
      price: '52',
      tag: 'Classic',
    },
    {
      id: 104,
      name: 'Tuna Melt Spicy',
      description: 'Warm tuna melt with spicy sauce',
      price: '55',
      tag: 'Spicy',
    },
    {
      id: 105,
      name: 'Broodjes Grillworst',
      description: 'Dutch-style bread with grillworst',
      price: '55',
      tag: '',
    },
    {
      id: 106,
      name: 'Msemen Grillworst',
      description: 'Moroccan msemen served with grillworst',
      price: '65',
      tag: 'Brunch',
    },
    {
      id: 107,
      name: 'Panini Tuna Melt',
      description: 'Panini with tuna and melted cheese',
      price: '50',
      tag: '',
    },
    {
      id: 108,
      name: 'Panini Tuna Melt Spicy',
      description: 'Panini with tuna, melted cheese and spicy sauce',
      price: '55',
      tag: 'Spicy',
    },
    {
      id: 109,
      name: 'Panini Chicken with Cheese',
      description: 'Panini with chicken and cheese',
      price: '52',
      tag: 'Popular',
    },
    {
      id: 110,
      name: 'Panini Spicy Chicken with Cheese',
      description: 'Panini with spicy chicken and cheese',
      price: '52',
      tag: 'Spicy',
    },
    {
      id: 111,
      name: 'Panini au Pesto de Mozzarella',
      description: 'Panini with pesto and mozzarella',
      price: '49',
      tag: 'Italian',
    },
    {
      id: 112,
      name: 'Sandwich au Poulet',
      description: 'Chicken sandwich served Benny’s style',
      price: '52',
      tag: '',
    },
    {
      id: 113,
      name: 'Burrata Toast',
      description: 'Toast with burrata',
      price: '55',
      tag: 'Fresh',
    },
    {
      id: 114,
      name: 'Toast Saumon',
      description: 'Toast with salmon',
      price: '55',
      tag: 'Signature',
    },
    {
      id: 115,
      name: 'Toast Avocat avec Œuf',
      description: 'Toast with avocado and egg',
      price: '55',
      tag: 'Fresh',
    },
    {
      id: 116,
      name: 'Msemen au Fromage',
      description: 'Moroccan msemen with cheese',
      price: '32',
      tag: '',
    },
    {
      id: 117,
      name: 'Msemen Nutella',
      description: 'Moroccan msemen with Nutella',
      price: '30',
      tag: 'Sweet',
    },
    {
      id: 118,
      name: 'Msemen au Miel',
      description: 'Moroccan msemen with honey',
      price: '25',
      tag: 'Classic',
    },
    {
      id: 119,
      name: 'Msemen Tuna Melt',
      description: 'Moroccan msemen with tuna and melted cheese',
      price: '52',
      tag: '',
    },
  ],

  hotCoffee: [
    {
      id: 201,
      name: 'Espresso',
      description: 'Strong classic espresso shot',
      price: '23',
      tag: 'Classic',
    },
    {
      id: 202,
      name: 'Ristretto',
      description: 'Short and intense espresso shot',
      price: '20',
      tag: '',
    },
    {
      id: 203,
      name: 'Double Espresso',
      description: 'Double shot of espresso',
      price: '28',
      tag: '',
    },
    {
      id: 204,
      name: 'Macchiato',
      description: 'Espresso marked with milk foam',
      price: '25',
      tag: '',
    },
    {
      id: 205,
      name: 'Americano M',
      description: 'Medium classic black coffee',
      price: '28',
      tag: '',
    },
    {
      id: 206,
      name: 'Americano L',
      description: 'Large classic black coffee',
      price: '35',
      tag: '',
    },
    {
      id: 207,
      name: 'Cappuccino M',
      description: 'Medium cappuccino with steamed milk and foam',
      price: '28',
      tag: 'Classic',
    },
    {
      id: 208,
      name: 'Cappuccino L',
      description: 'Large cappuccino with steamed milk and foam',
      price: '35',
      tag: 'Classic',
    },
    {
      id: 209,
      name: 'Latte M',
      description: 'Medium latte with smooth steamed milk',
      price: '28',
      tag: '',
    },
    {
      id: 210,
      name: 'Latte L',
      description: 'Large latte with smooth steamed milk',
      price: '35',
      tag: '',
    },
    {
      id: 211,
      name: 'Latte Macchiato',
      description: 'Layered coffee with milk',
      price: '28',
      tag: '',
    },
    {
      id: 212,
      name: 'Flat White',
      description: 'Smooth espresso with fine milk foam',
      price: '30',
      tag: '',
    },
    {
      id: 213,
      name: 'Mocha',
      description: 'Coffee with chocolate and milk',
      price: '35',
      tag: 'Chocolate',
    },
    {
      id: 214,
      name: 'Spanish Latte',
      description: 'Sweet Spanish-style latte',
      price: '30',
      tag: 'Signature',
    },
    {
      id: 215,
      name: 'Cortado',
      description: 'Espresso balanced with warm milk',
      price: '28',
      tag: '',
    },
    {
      id: 216,
      name: 'Bonbon',
      description: 'Sweet coffee with condensed milk style',
      price: '30',
      tag: 'Sweet',
    },
    {
      id: 217,
      name: 'Chai Latte',
      description: 'Warm spiced chai latte',
      price: '35',
      tag: 'Spiced',
    },
  ],

  icedCoffee: [
    {
      id: 301,
      name: 'Iced Americano',
      description: 'Cold Americano coffee',
      price: '30',
      tag: 'Classic',
    },
    {
      id: 302,
      name: 'Iced Latte',
      description: 'Cold latte coffee',
      price: '32',
      tag: 'Classic',
    },
    {
      id: 303,
      name: 'Iced Mocha',
      description: 'Cold mocha coffee with chocolate',
      price: '38',
      tag: 'Chocolate',
    },
    {
      id: 304,
      name: 'Iced Spanish Latte',
      description: 'Cold Spanish-style latte',
      price: '45',
      tag: 'Signature',
    },
    {
      id: 305,
      name: 'Iced Spanish Mocha Latte',
      description: 'Cold Spanish mocha latte with chocolate notes',
      price: '48',
      tag: 'Popular',
    },
  ],

  teaChocolate: [
    {
      id: 401,
      name: 'Moroccan Tea',
      description: 'Traditional Moroccan tea',
      price: '20',
      tag: 'Tea',
    },
    {
      id: 402,
      name: 'English Breakfast Tea',
      description: 'Classic English breakfast tea',
      price: '30',
      tag: 'Tea',
    },
    {
      id: 403,
      name: 'Ginger Tea',
      description: 'Warm ginger tea',
      price: '25',
      tag: 'Tea',
    },
    {
      id: 404,
      name: 'Hot Chocolate M',
      description: 'Medium hot chocolate',
      price: '30',
      tag: 'Chocolate',
    },
    {
      id: 405,
      name: 'Hot Chocolate L',
      description: 'Large hot chocolate',
      price: '37',
      tag: 'Chocolate',
    },
  ],

  matcha: [
    {
      id: 501,
      name: 'Matcha Latte',
      description: 'Smooth classic matcha latte',
      price: '55',
      tag: 'Classic',
    },
    {
      id: 502,
      name: 'Matcha Strawberry',
      description: 'Matcha with strawberry flavor',
      price: '60',
      tag: 'Fruity',
    },
    {
      id: 503,
      name: 'Matcha Blueberry',
      description: 'Matcha with blueberry flavor',
      price: '60',
      tag: 'Fruity',
    },
    {
      id: 504,
      name: 'Matcha Mango',
      description: 'Matcha with mango flavor',
      price: '60',
      tag: 'Fruity',
    },
    {
      id: 505,
      name: 'Matcha White Chocolate',
      description: 'Matcha with white chocolate flavor',
      price: '60',
      tag: 'Sweet',
    },
  ],

  juicesSmoothies: [
    {
      id: 601,
      name: 'Orange Juice',
      description: 'Fresh orange juice',
      price: '30',
      tag: 'Fresh',
    },
    {
      id: 602,
      name: 'Mango Smoothie',
      description: 'Fresh mango smoothie',
      price: '39',
      tag: 'Smoothie',
    },
    {
      id: 603,
      name: 'Strawberry Smoothie',
      description: 'Fresh strawberry smoothie',
      price: '39',
      tag: 'Smoothie',
    },
    {
      id: 604,
      name: 'Mango Strawberry Smoothie',
      description: 'Mango and strawberry smoothie',
      price: '49',
      tag: 'Smoothie',
    },
    {
      id: 605,
      name: 'Avocado Smoothie',
      description: 'Creamy avocado smoothie',
      price: '49',
      tag: 'Smoothie',
    },
    {
      id: 606,
      name: 'Banana Smoothie',
      description: 'Creamy banana smoothie',
      price: '39',
      tag: 'Smoothie',
    },
    {
      id: 607,
      name: 'Lemon Juice',
      description: 'Fresh lemon juice',
      price: '30',
      tag: 'Fresh',
    },
  ],

  signatureDrinks: [
    {
      id: 701,
      name: 'Blue Curacao Hawaii',
      description: 'Blue tropical signature drink',
      price: '69',
      tag: 'Signature',
    },
    {
      id: 702,
      name: 'Blue Sky',
      description: 'Refreshing blue signature drink',
      price: '65',
      tag: 'Signature',
    },
    {
      id: 703,
      name: 'Bob Drink',
      description: 'Benny’s colorful signature drink',
      price: '69',
      tag: 'Signature',
    },
  ],

  mojitos: [
    {
      id: 801,
      name: 'Classic Mojito',
      description: 'Classic fresh mojito',
      price: '49',
      tag: 'Classic',
    },
    {
      id: 802,
      name: 'Mango Mojito',
      description: 'Fresh mojito with mango flavor',
      price: '49',
      tag: 'Fruity',
    },
    {
      id: 803,
      name: 'Strawberry Mojito',
      description: 'Fresh mojito with strawberry flavor',
      price: '49',
      tag: 'Fruity',
    },
    {
      id: 804,
      name: 'Blueberry Mojito',
      description: 'Fresh mojito with blueberry flavor',
      price: '49',
      tag: 'Fruity',
    },
    {
      id: 805,
      name: 'Blue Mojito',
      description: 'Fresh blue mojito',
      price: '55',
      tag: 'Signature',
    },
  ],

  icedTea: [
    {
      id: 901,
      name: 'White Mulberry Iced Tea',
      description: 'Refreshing white mulberry iced tea',
      price: '45',
      tag: 'Refreshing',
    },
    {
      id: 902,
      name: 'Blue Butterfly Iced Tea',
      description: 'Refreshing blue butterfly iced tea',
      price: '45',
      tag: 'Refreshing',
    },
    {
      id: 903,
      name: 'Blueberry Iced Tea',
      description: 'Refreshing blueberry iced tea',
      price: '50',
      tag: 'Fruity',
    },
  ],

  milkshakes: [
    {
      id: 1001,
      name: 'Milkshakes',
      description: 'All milkshake flavors',
      price: '49',
      tag: 'All Flavors',
    },
  ],

  desserts: [
    {
      id: 1101,
      name: 'Chocolat San Sebastian',
      description: 'San Sebastian cheesecake with chocolate',
      price: '65',
      tag: 'Cheesecake',
    },
    {
      id: 1102,
      name: 'Normal San Sebastian',
      description: 'Classic San Sebastian cheesecake',
      price: '59',
      tag: 'Cheesecake',
    },
    {
      id: 1103,
      name: 'Pistachio San Sebastian',
      description: 'San Sebastian cheesecake with pistachio',
      price: '65',
      tag: 'Pistachio',
    },
    {
      id: 1104,
      name: 'Lotus San Sebastian',
      description: 'San Sebastian cheesecake with Lotus flavor',
      price: '65',
      tag: 'Lotus',
    },
    {
      id: 1105,
      name: 'Normal Cookies',
      description: 'Classic cookie',
      price: '39',
      tag: 'Cookie',
    },
    {
      id: 1106,
      name: 'Pistachio Cookies',
      description: 'Cookie with pistachio flavor',
      price: '42',
      tag: 'Cookie',
    },
    {
      id: 1107,
      name: 'Date Cake',
      description: 'Soft date cake',
      price: '35',
      tag: 'Cake',
    },
    {
      id: 1108,
      name: 'Carrot Cake',
      description: 'Rich carrot cake slice',
      price: '59',
      tag: 'Cake',
    },
    {
      id: 1109,
      name: 'Seasonal Fruits Poffertjes',
      description: 'Dutch poffertjes with seasonal fruits',
      price: '45',
      tag: 'Dutch Style',
    },
    {
      id: 1110,
      name: 'Strawberry Nutella Poffertjes',
      description: 'Dutch poffertjes with strawberry and Nutella',
      price: '45',
      tag: 'Dutch Style',
    },
    {
      id: 1111,
      name: 'Butter and Powder Sugar Poffertjes',
      description: 'Dutch poffertjes with butter and powdered sugar',
      price: '39',
      tag: 'Dutch Style',
    },
    {
      id: 1112,
      name: 'Pistachio Brownie',
      description: 'Brownie with pistachio flavor',
      price: '38',
      tag: 'Brownie',
    },
    {
      id: 1113,
      name: 'Apple Pie',
      description: 'Classic apple pie',
      price: '59',
      tag: 'Classic',
    },
  ],

  energyBalls: [
    {
      id: 1201,
      name: 'Pistachio Energy Balls',
      description: 'Small pistachio energy bite',
      price: '15',
      tag: 'Energy',
    },
    {
      id: 1202,
      name: 'Chocolat Energy Balls',
      description: 'Small chocolate energy bite',
      price: '12',
      tag: 'Energy',
    },
    {
      id: 1203,
      name: 'Coconut Energy Balls',
      description: 'Small coconut energy bite',
      price: '12',
      tag: 'Energy',
    },
  ],
};

export const testimonials = [
  {
    id: 1,
    name: 'Sarah M.',
    role: 'Regular Customer',
    text: "Benny's has become my second home. The arches, the aroma, the atmosphere - it's like stepping into a warm hug every morning.",
    rating: 5,
  },
  {
    id: 2,
    name: 'Ahmed K.',
    role: 'Coffee Enthusiast',
    text: "The best coffee in town, hands down. Their signature blend is absolutely divine. I've tried cafés all over Morocco, and Benny's is unmatched.",
    rating: 5,
  },
  {
    id: 3,
    name: 'Emma L.',
    role: 'Digital Nomad',
    text: "Perfect spot for remote work. Great wifi, amazing coffee, and the most beautiful interior I've ever seen in a café. Those arches are iconic!",
    rating: 5,
  },
  {
    id: 4,
    name: 'Youssef B.',
    role: 'Architect',
    text: "As an architect, I appreciate the stunning design. The upside-down U arches create such a unique, cozy atmosphere. And the coffee? Chef's kiss!",
    rating: 5,
  },
];

export const features = [
  {
    id: 1,
    icon: '☕',
    title: 'Premium Beans',
    description: 'Ethically sourced from the finest farms around the world',
  },
  {
    id: 2,
    icon: '🏛️',
    title: 'Iconic Architecture',
    description: 'Our signature arches create a warm, Instagram-worthy space',
  },
  {
    id: 3,
    icon: '👨‍🍳',
    title: 'Expert Baristas',
    description: 'Trained professionals crafting your perfect cup every time',
  },
  {
    id: 4,
    icon: '🥐',
    title: 'Fresh Pastries',
    description: 'Baked daily in-house with the finest ingredients',
  },
];

export const socialLinks = [
  { name: 'Instagram', url: 'https://instagram.com/bennyscoffee', icon: 'instagram' },
  { name: 'Facebook', url: 'https://facebook.com/bennyscoffee', icon: 'facebook' },
  { name: 'TikTok', url: 'https://tiktok.com/@bennyscoffee', icon: 'tiktok' },
];

export const contactInfo = {
  address: 'Iberia, Tangier, Morocco',
  phone: '+212 6 10 70 50 53',
  email: 'contact@bennyscoffee.ma',
  hours: {
    weekdays: '8:00 AM - 02:00 PM',
    weekends: '8:00 AM - 03:00 PM',
  },
};

export const navLinks = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Menu', href: '#menu' },
  { name: 'Gallery', href: '#gallery' },
  { name: 'Contact', href: '#contact' },
];